# Generated by Django 4.2.11 on 2026-01-29 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_alter_student_hash_fields'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentparent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(related_name='parents', through='parents.StudentParent', to='students.student'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentparent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='parents.parent'),
        ),
        migrations.AlterField(
            model_name='studentparent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='studentparent',
            constraint=models.UniqueConstraint(fields=('student', 'parent'), name='uniq_student_parent'),
        ),
    ]
